# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Handling Reading
safe:                 true
include:              [".htaccess"]
exclude:              [
  "*/README.md",
  "Gemfile",
  "Gemfile.lock",
  "Makefile",
  "node_modules",
  "README.md",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
url:     "https://dejangrubisic.github.io"
# baseurl: "/staging"
show_dir_listing: false

# Outputting
permalink:     /:year/:title/
timezone:      null

quiet:    false
verbose:  false
defaults:
  -
    values:
      layout: "default"

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Extensions
plugins:
  - jekyll-redirect-from  # enable "refirect_from" in front matter
  - jekyll-github-metadata  # add 'site.github' github metadata

sass:
  style: compressed

# Styling
jumbotron_min_height: 300
jumbotron_max_height: 500
jumbotron_content_gap: 30

# logos for social networks. Obfuscated names to prevent simple rule-based
# ad blocking.
social_images:
  facebook:  /img/atw/8dd8ef87f47c829d6dc1a491e06929bb.png
  github:    /img/atw/1ed153fe358ed0d5d38553df372687d6.png
  linkedin:  /img/atw/5c95cc032204cec372b9d9ccbd84191d.png

copyright:
  owner: Chris Cummins
  year: 2013-2020
  license: MIT (https://github.com/ChrisCummins/chriscummins.github.io/blob/master/LICENSE)
